cashQTYs:

defaultCash: 100
spareWalletDefault: 0
defaultCurrencyName: "International Currency"
defaultLang: "EN"

playerLanguages:

currencies:

exchangeFee: 0 #in %
exchangeFeeFixed: 0 #added after "Exchange Fee", in $ on "to" currency

ItemSellValues:
  DIRT: 1