cashQTYs:

defaultCash: 100
spareWalletDefault: 0
defaultCurrencyName: "International Currency"
defaultLang: "EN"
connectVault: true # Connects vault if vault is installed

playerLanguages:

currencies:

exchangeFee: 0 #in %
exchangeFeeFixed: 0 #added after "Exchange Fee", in $ on "to" currency

moneyItemName: "&6Money"
ItemSellValues:
  DIRT: 1